### ISSUE TITLE
NoClassDefFoundError

### ISSUE THREAD

**Issue by agent00jackson** [alivcor/SMORK#2]
Hi,
Got SMORK building, took the jar from ./target/scala-2.11 and loaded it into the spark-shell with:
`:require smork_2.11-1.0.jar`

I was able to import without any errors either, however I got this stack trace when trying to create the SMOTE object:
```
scala> val smote = new SMOTE()
java.lang.NoClassDefFoundError: org/apache/spark/ml/util/MLWritable$class
  at com.iresium.ml.SMOTE.<init>(SMOTE.scala:16)
  at com.iresium.ml.SMOTE.<init>(SMOTE.scala:35)
```

I would note I'm using spark 3.0.0-preview2, so that could be a contributing factor, and I'm using this dockerfile I wrote to run spark, if my environment could be a part of the problem:
https://github.com/agent00jackson/spring2020-big-data/blob/master/Dockerfile

**Comment by alivcor** [comment]
@agent00jackson can you try doing `sbt clean run` in the cloned directory?

**Comment by agent00jackson** [comment]
Got it running after changing the scala and spark versions inside of the build.sbt. I'm not familiar enough with scala/sbt, but if there was a way to automatically get the spark/scala versions from the environment, that would be awesome.
